name: Build and deploy Hugo site to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.151.2'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Debug: inspect generated public folder
        shell: bash
        run: |
          echo "=== WORKSPACE ==="
          pwd
          echo "=== LS repo root (first 200 entries) ==="
          ls -la | head -n 200 || true
          echo "=== public dir listing ==="
          if [ -d ./public ]; then ls -la ./public || true; else echo "public directory missing"; fi
          echo "=== public size ==="
          if [ -d ./public ]; then du -sh ./public || true; fi
          echo "=== head of public/index.html ==="
          if [ -f ./public/index.html ]; then head -n 60 ./public/index.html || true; else echo "public/index.html missing"; fi

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./public
          publish_branch: gh-pages
          allow_empty_commit: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
